# Generated by Django 2.0 on 2017-12-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('email', models.CharField(max_length=50, verbose_name='账户名称')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('deleted', models.IntegerField(default=0, verbose_name='是否删除')),
                ('emailVerified', models.IntegerField(default=0, verbose_name='邮箱是否验证')),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
