# Generated by Django 2.0 on 2017-12-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getofferapi', '0005_auto_20171228_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdpartyoffer',
            name='payoutValue',
            field=models.CharField(default=0, max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
