# Generated by Django 2.0 on 2018-01-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyOffer',
            fields=[
                ('id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('userId', models.IntegerField(max_length=11)),
                ('taskId', models.IntegerField(max_length=11)),
                ('status', models.IntegerField(max_length=11)),
                ('offerId', models.TextField()),
                ('name', models.CharField(default='', max_length=256)),
                ('previewLink', models.TextField()),
                ('trackingLink', models.TextField()),
                ('countryCode', models.TextField()),
                ('payoutMode', models.IntegerField(default=1, max_length=11)),
                ('payoutValue', models.CharField(default=0, max_length=11)),
                ('category', models.TextField()),
                ('carrier', models.TextField()),
                ('platform', models.TextField()),
                ('detail', models.TextField()),
            ],
            options={
                'db_table': 'ThirdPartyOffer',
            },
        ),
    ]
